language: node_js
node_js:
- '4.6'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: m35PKx0pYqwOq/99yO+Eas+49IA0WpJGEbtX4jhQgLXpYT09+QN1ZrqyH7bwzI1h0X/ivVThuNl7izewlSlwiru6Q+PtSek/zGIPKT3D/i0fOs4PzKnfe9xoIQhRd6o+MRfgrllzwwZQstYRe7L/XezeXUM0zlC0XkE6vJ+lV6g=
  - secure: ERxa47i3B7z9RkA8vls9dCNVbKvfS91WVYJcP3WmfZdtUTFd4jVeTrabGZJ6yNDhBVO8IDhUX+WEp3pGT0F+qYeLF6unfu7GjAdZB129+iispDblYTlnHMii7UC/hRelEKvIrGjSMg/Blv5jZMS/3TDBur2QEtx7G9ap6pLKghg=
